# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180129_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_hot',
            field=models.BooleanField(default=True, verbose_name='热门课程'),
        ),
    ]
