# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司名称')),
                ('telephone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('address', models.CharField(max_length=50, verbose_name='通信地址')),
                ('qqNumber', models.IntegerField(max_length=20, verbose_name='咨询QQ')),
                ('comSlogan', models.CharField(max_length=100, verbose_name='公司标语')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
    ]
