# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firminfo',
            name='qqNumber',
            field=models.IntegerField(verbose_name='咨询QQ'),
        ),
    ]
