# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0002_auto_20180124_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=32, unique=True, verbose_name='菜单名')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码')),
                ('url', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sysconf.Menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='通信地址'),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='comName',
            field=models.CharField(max_length=50, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='comSlogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司标语'),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='qqNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='咨询QQ'),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='联系电话'),
        ),
    ]
