# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0003_auto_20180124_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '导航菜单', 'verbose_name_plural': '导航菜单'},
        ),
        migrations.AddField(
            model_name='menu',
            name='sortNume',
            field=models.IntegerField(blank=True, default=0, help_text='按照数字排序，0优先级最高', null=True, verbose_name='显示顺序'),
        ),
    ]
