# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0005_auto_20180124_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['sortNumber'], 'verbose_name': '导航菜单', 'verbose_name_plural': '导航菜单'},
        ),
        migrations.AddField(
            model_name='menu',
            name='quickLink',
            field=models.BooleanField(default=False, verbose_name='底部快速导航'),
        ),
    ]
